# Generated by Django 5.1 on 2024-08-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.CharField(default="", max_length=50),
        ),
    ]
