# Generated by Django 5.1 on 2024-08-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentence",
            name="room",
        ),
        migrations.AlterField(
            model_name="player",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.room"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.player"
            ),
        ),
    ]
